### ISSUE TITLE
Can't run the game

### ISSUE THREAD

**Issue by fenidaz** [owenashurst/agar.io-clone#433]
Hello, i follow the instruction step by step, but i cant run the game help :c 
when i put "npm start" nothing happens :c 

Help me!!

https://gist.github.com/IvoFacundo/7486fdcc5fef434619865f0238bd5d94 Nothing :c

**Comment by abalabahaha** [comment]
Are you stopping the build manually? Your computer seems pretty slow, so the build process may take a while.

The entire build should look similar to:
```
[2:38:01] Using gulpfile ~/Downloads/agar.io-clone/gulpfile.js
[2:38:01] Starting 'lint'...
[2:38:01] Starting 'move-client'...
[2:38:03] Finished 'lint' after 2.08 s
[2:38:03] Starting 'build-server'...
[2:38:03] Starting 'test'...
[2:38:03] Finished 'test' after 3.43 ms
[2:38:03] Starting 'todo'...
[2:38:03] Finished 'todo' after 2.91 ms


  util.js
    #massToRadius
      ✓ should return non-zero radius on zero input
      ✓ should convert masses to a circle radius
    #validNick
[10:38:04] Finished 'build-server' after 586 ms
      ✓ should allow empty player nicknames
      ✓ should allow ascii character nicknames
      ✓ should disallow unicode-dependent alphabets
      ✓ should disallow spaces in nicknames
    #log
      ✓ should compute the log_{base} of a number
    #getDistance
      ✓ should return a positive number


  8 passing (33ms)

[2:38:04] Finished 'move-client' after 2.68 s
[2:38:04] Starting 'build-client'...
[2:38:06] Version: webpack 1.13.1
 Asset    Size  Chunks             Chunk Names
app.js  225 kB       0  [emitted]  main
[2:38:06] Finished 'build-client' after 2 s
[2:38:06] Starting 'build'...
[2:38:06] Finished 'build' after 2.69 μs
[2:38:06] Starting 'run'...
[2:38:06] Finished 'run' after 1.82 ms
[2:38:06] [nodemon] 1.9.2
[2:38:06] [nodemon] to restart at any time, enter `rs`
[2:38:06] [nodemon] watching: *.*
[2:38:06] [nodemon] starting `node ./server/server.js config.json`
[DEBUG] Listening on *:3000
```

**Comment by IvoFacundo** [comment]
no i dont stop it , the process close on "8 passing (4s)" -see on the gist-

and nothing happens :( u can give me ur project? to compare, maybe i have a error because im a noob on node, only if u want of course

**Comment by abalabahaha** [comment]
I just cloned the repo...

What NodeJS version do you have?

**Comment by IvoFacundo** [comment]
i have v4.4.5 LTS

**Comment by IvoFacundo** [comment]
@abalabahaha  sorry but im new on GH, sorry, how i can download ur repo?

**Comment by abalabahaha** [comment]
[I downloaded the repo this very issue is on](https://github.com/huytd/agar.io-clone)

Noticed gulp took 50 seconds to lint on your computer, but only 2 seconds on mine... It could be your computer is too slow/overloaded

**Comment by IvoFacundo** [comment]
Microsoft Windows [Versión 6.1.7601]
Copyright (c) 2009 Microsoft Corporation. Reservados todos los derechos.

C:\Users\BreakinBad>cd Downloads

C:\Users\BreakinBad\Downloads>cd agar.io-clone-master

C:\Users\BreakinBad\Downloads\agar.io-clone-master>npm start

> agar-clone@1.0.0 start C:\Users\BreakinBad\Downloads\agar.io-clone-master
> gulp run

[19:37:41] Using gulpfile ~\Downloads\agar.io-clone-master\gulpfile.js
[19:37:41] Starting 'lint'...
[19:37:41] Starting 'move-client'...
[19:38:12] Finished 'lint' after 31 s
[19:38:12] Starting 'build-server'...
[19:38:12] Starting 'test'...
[19:38:12] Finished 'test' after 18 ms
[19:38:12] Starting 'todo'...
[19:38:12] Finished 'todo' after 33 ms
[19:38:15] Finished 'move-client' after 33 s
[19:38:15] Starting 'build-client'...


  util.js
    #massToRadius
      V should return non-zero radius on zero input
      V should convert masses to a circle radius
    #validNick
[19:38:21] Finished 'build-server' after 9.07 s
      V should allow empty player nicknames
      V should allow ascii character nicknames
      V should disallow unicode-dependent alphabets
      V should disallow spaces in nicknames
    #log
      V should compute the log_{base} of a number
    #getDistance
      V should return a positive number


  8 passing (1s)


C:\Users\BreakinBad\Downloads\agar.io-clone-master>

Nothing bro :c the project stop it  :C, try reinstalling all the dependencies and restart my pc

**Comment by sunnyguan** [comment]
Try using npm install before you use npm start

**Comment by IvoFacundo** [comment]
@sunnyguan Yes! i do it this, but nothing... ;( (sorry for my english) :D

**Comment by sunnyguan** [comment]
@IvoFacundo can you post the results for doing npm install?

**Comment by IvoFacundo** [comment]
@sunnyguan @abalabahaha No more problems, the game run normally now :) i download other repo, uploaded by other user and works! ty anyway :3 (sorry for my english e.e) 

But i have a problem in the game now:
in game the div or span (Score) show me "Score: Null" is a error? dont show me for example 230, or 4000, always show Null
(sorry for my english AGAIN e.e)

**Comment by Ayelis** [comment]
Other issues should be addressed in a new Issue ticket. If you can run the game now, this issue should be closed.

**Comment by Syedayesha** [comment]
@IvoFacundo can you please give the link where you downloaded the other repo....because I am also getting the same issue.......

**Comment by owenashurst** [comment]
Checkout master, the whole project has had all of its packages upgraded and fixed. The demo server @ heroku is now up and working.
