### ISSUE TITLE
Can't play

### ISSUE THREAD

**Issue by sonderlau** [owenashurst/agar.io-clone#450]
I did what you said in the wiki page, and "gulp run"
i could open the page  localhost:3000
but when i clicked the Play button,there's nothing happened, i also see errors in cosole

like:

Uncaught SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

hope you can reply me , thanks

**Comment by TheCodeCrafter** [comment]
I HAVE THE EXACT SAME PROBLEM!

**Comment by owenashurst** [comment]
Check master. The project has undergone a whole upgrade of its packages. It works locally now and currently deployed to Heroku for demoing.
