### ISSUE TITLE
Publishing to domain

### ISSUE THREAD

**Issue by valonymeri** [owenashurst/agar.io-clone#480]
Hi. very nice work, but i cant publish it on domain only in localhost. how do i make it run on public domain i am using windows server.

**Comment by vikramdurai** [comment]
you can deploy to a domain using [Heroku or Bluemix](https://github.com/huytd/agar.io-clone#installation)

**Comment by valonymeri** [comment]
Thx for the replay.  Do i use Heroku or Bluemix even if I want to deploy on my own dedicated windows server and my own domain.

**Comment by PortPixel** [comment]
You could deploy on your own server if you want, you just need to install node.js and dependencies, then configure your firewall/router to forward requests to the the correct port on your computer.

**Comment by valonymeri** [comment]
I did deploy but it starts on localhost:3000 how to start it on public domain. Thx for the reply

**Comment by PortPixel** [comment]
You need to foward external ip address (xxx.xxx.xxx.xxx) to your computer's internal ip address on your network (usually 192.168.xxx.xxx). This can usually be done in your router's configuration page

**Comment by valonymeri** [comment]
Should i do that in my dedicated server.  (Godaddy) and can is it accesible than from all the world.  If u can please explain a bit i would appreciate it very much.  Thank you very much

**Comment by PortPixel** [comment]
I don't know how to set it up on a GoDaddy server, but I'm sure if you look it up there are tutorial on how to do it.

**Comment by valonymeri** [comment]
I've looked up everywhere i cant seem to find the solution, can you please find me a solution how to publish this app on windows server to and point to domain. i would appreciate it very much

**Comment by vikramdurai** [comment]
you can search youtube.....

**Comment by baiplr** [comment]
If the app is running on port 3000, and you want it to appear when you access port 80 (when you type in the domain name), then follow [this guide.](https://coderwall.com/p/plejka/forward-port-80-to-port-3000)
