### ISSUE TITLE
Player freezes a lot

### ISSUE THREAD

**Issue by Konzt** [owenashurst/agar.io-clone#482]
Hi. i have published game but it freezes a lot, does any one have any idea why.

**Comment by geopi** [comment]
link of the server ? might be related with the bandwith usage .

**Comment by NOperatingSystem** [comment]
Thx for the replay.
The link is www.targ.io . Player freezes only on chrome, firefox,opera but not in internet explorer. I did look in network in browser developer tools and saw a lot of connection on chrome, firefox and not stopping.
I am using windows server iis 8.5

**Comment by geopi** [comment]
indeed it lags (i use chrome). Did you edit the code and which branch did you use ?
It looks like it is client related (app.js) unless you edited the rate at which the server sends visible entities to the client.

try a deploy in heroku, its fast, simple and free, just to have a second view .

**Comment by TheCodeCrafter** [comment]
I just tested using Chrome. No lag here. I think you all are going bonkers ;)

LOL. Maybe it's your Chrome version. MAKE SURE IT IS UP TO DATE!

**Comment by valonymeri** [comment]
Nahh i changed the server thats why there is no lag now
