### ISSUE TITLE
Build for Mobile

### ISSUE THREAD

**Issue by nhutlv01** [owenashurst/agar.io-clone#483]
Like Agario and Slitherio.
Can we build this project into mobile devices (not play on web) ?
If it can. Can you give me an advice about the tool to build.

Thanks all!

**Comment by pctripsesp** [comment]
https://play.google.com/store/apps/details?id=com.miniclip.agar.io&hl=en

https://play.google.com/store/apps/details?id=air.com.hypah.io.slither&hl=en

**Comment by Nikitaw99** [comment]
@pctripsesp They weren't asking for the download links for the games, they asked how to build their agario-clone game on android/ios/mobile.

**Comment by huytd** [comment]
@nhutlv01 yeah you can. If you take a look at the [Game Architecture](https://github.com/huytd/agar.io-clone/wiki/Game-Architecture) document in Wiki, you can see the project has 2 parts: The server (written in Node) and the game client (using HTML5 canvas). What you can do is to replace the HTML5 canvas client with mobile code logic (based on some engine or anything you want).

I have to admit that this server is not good enough to build a real game on it, but the basic idea is just the same.

**Comment by geopi** [comment]
Check phonegap to use javascript / css / html client for crossplatform mobile app.

**Comment by jasonchitla** [comment]
@huytd You say this server is not good enough to build a real game on it. So, what are the things you would have in place in order to say this server is good enough? I am about to make an io game that also includes a mobile client, and I'm curious as to what you would do differently. For example, is it security of the servers, is it the architecture you would change, or what?

**Comment by owenashurst** [comment]
> @huytd You say this server is not good enough to build a real game on it. So, what are the things you would have in place in order to say this server is good enough? I am about to make an io game that also includes a mobile client, and I'm curious as to what you would do differently. For example, is it security of the servers, is it the architecture you would change, or what?

If you have to ask, don't do it.
