### ISSUE TITLE
Can you help me?

### ISSUE THREAD

**Issue by ghost** [owenashurst/agar.io-clone#504]
Hello! Can I talk with you? Can you help me with your agar.io? Sorry, I'm from Russia. My English language is not good.

**Comment by baiplr** [comment]
Hello,
Please do not start a new issue asking for help without specifying what you would like help with. If you have a problem with this project, then please provide details.

**Comment by GameDeve1oper** [comment]
Help please fix the bug with eating your opponents and how to make the background a picture? Just have a picture and have it repeat.
