### ISSUE TITLE
I can't run the project properly(nothing shows up)

### ISSUE THREAD

**Issue by LittleTree213** [owenashurst/agar.io-clone#511]
Hi
with great thanks for your project:)

I had several problems running the project that solved them properly.
Remains one:
> rimraf src/main/webapp/dist

'rimraf' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! portfolio@1.0.0 clean: `rimraf src/main/webapp/dist`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the portfolio@1.0.0 clean script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Nahal_Boroumand\AppData\Roaming\npm-cache\_logs\2018-01-08T13_58_29_929Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! portfolio@1.0.0 build: `npm run clean && parallel-webpack --max-retries=3 --config config/webpack.build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the portfolio@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Nahal_Boroumand\AppData\Roaming\npm-cache\_logs\2018-01-08T13_58_30_199Z-debug.log
------------------------------------------------------------------------
BUILD FAILURE
------------------------------------------------------------------------
Total time: 2:14.744s
Finished at: Mon Jan 08 05:58:30 PST 2018
Final Memory: 12M/99M
------------------------------------------------------------------------
Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.6:npm (npm run build) on project agario: Failed to run task: 'npm run build' failed. org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1) -> [Help 1]

To see the full stack trace of the errors, re-run Maven with the -e switch.
Re-run Maven using the -X switch to enable full debug logging.

For more information about the errors and possible solutions, please read the following articles:
[Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
--------------------------------------------------------------------------------------
this shows after minutes when I run this maven project
on netbeans IDE with maven 3.1
my computer os is windows 10
my browser is chrome

what should I do to play @localhost:3000

regards!

**Comment by dotgodly** [comment]
Try following [this](https://github.com/huytd/agar.io-clone/wiki/Setup), and let us know what happens.
