### ISSUE TITLE
Resolution problem.

### ISSUE THREAD

**Issue by r8w9a5k** [owenashurst/agar.io-clone#520]
Hello, thank you for this project. It's amazing !

Anyway, I have problem in resolution. When I run the game in browser, resolution changes every second and the game becomes very hard to play. I tried full screen mode, smaller screen and the problem is still here.

Here I am uploading screens.
![image](https://user-images.githubusercontent.com/28980824/41846249-6778f39e-7876-11e8-9f5e-29aa662a4564.png)

![image](https://user-images.githubusercontent.com/28980824/41846257-71b70332-7876-11e8-91f7-a427af1e8277.png)

I am running latest Chrome and win 10.

Thanks in advance.

**Comment by dotgodly** [comment]
'client/js/app.js' line 232 when #status is updated, causes this.

**Comment by r8w9a5k** [comment]
@dotgodly Thank you, it works great !
