### ISSUE TITLE
I want to use this in my school project, could i fork this?

### ISSUE THREAD

**Issue by ldy2119** [owenashurst/agar.io-clone#525]
I want to use this in my school project, could i fork this?

**Comment by huytd** [comment]
Please feel free to fork it, but I would recommend take a look at https://github.com/huytd/agar.io-clone/wiki/Game-Architecture and implement it from scratch if you are doing something like school project (eventually, it's to learn something, right?)

The wiki article is outdated but it's closest to the first version of this code, which is simple enough.
