### ISSUE TITLE
Allowing trough port 80 with other websites 

### ISSUE THREAD

**Issue by ghost** [owenashurst/agar.io-clone#526]
Hi,

Sorry for my newbie question. But i was looking to host this on my server for a school project im doing.
Anyways im running the game with gulp as instructed in the documetation.
But since its running its own server i cant use port 80 and still have my other websites running. Is there any other way around this?

**Comment by panther142** [comment]
Does it nees to run on port 80? Could you run it on 8080 instead?

**Comment by billotronic** [comment]
https://github.com/huytd/agar.io-clone/blob/master/config.json#L3

Set it to whatever port you want
