### ISSUE TITLE
Docker build fails ENOTDIR: not a directory,

### ISSUE THREAD

**Issue by carusooo** [owenashurst/agar.io-clone#536]
When I run a docker build
```shell
>  docker build -t agario_clone  --platform linux/amd64 .
```

I get an error like
```
#7 420.7 npm ERR! ENOTDIR: not a directory, open '/usr/src/app/node_modules/.staging/@types/eslint-scope-ac73784d/package.json'
```

I am running on an M1 mac to build the container (hence the platform specifier), some Google searching suggests that this error is due to using an old version of Node.js. Curious if anyone else has seen this

**Comment by carusooo** [comment]
I tried installing the missing `@types` packages, the same failures kept occurring
```
+        "@types/cors": "^2.8.13",
+        "@types/eslint": "^8.40.0",
+        "@types/eslint-scope": "^3.7.4",
+        "@types/minimatch": "^5.1.2",
```

I was able to get the build to complete by using the `node:8-onbuild` container, but that failed once deployed

**Comment by WrathofGod** [comment]
您好，已经收到您的简历，简历部门需要初筛，如果通过了两个工作日内会有通知。
