### ISSUE TITLE
Refactors from my fork

### ISSUE THREAD

**Issue by Zoldszemesostoros** [owenashurst/agar.io-clone#540]
A few months ago, I toyed with this project. I have made several server-side changes, including
 * Separating game logic into six files: food.js, virus.js, user.js, massFood.js, map.js, and server.js.
 * Using classes: 
     * Creating four classes: Food, User, MassFood, and Virus. `massFood.push({ /* lots of things */ })` becomes `massFood.push(new MassFood(playerFiring, cellIndex))`
     * Creating four other classes: FoodManager, MassFoodManager, UserManager, and VirusManager. These essentially act as a wrapper for the corresponding arrays (e.g. FoodManager for the foods array).
 * Separating spectators and players. Instead of spectators being players with 0 cells, there is a separate `spectators` array for them.
 * Removing duplicated code
 * Making variable names English instead of Spanish

I have also made a sort-of-working game replay feature.
I don't think every change should be upstreamed - I have got rid of some features I don't need, but others might, and I have made some changes to the protocol too - but I believe some of them can be useful. I can give you the source, or I can cherry-pick changes and submit PR-s if you are interested. I won't have too much time in July, so I can do the second option only in August.

**Comment by owenashurst** [comment]
Hi @Zoldszemesostoros this sounds like a great refactor. I strongly encourage you to submit a PR with the changes you've made. 

What kind of features did you remove? Definitely include the fundamental changes you bullet pointed.

**Comment by Zoldszemesostoros** [comment]
I will submit a PR next week.
> What kind of features did you remove? 

Logging using an database; variable colored food particles; variable sized viruses
